### ISSUE TITLE
 line 63: --data: command not found error

### ISSUE THREAD

**Issue by ghost** [lifehome/systemd-cfddns#3]
I set it in the Global API Key.
However, I get an error and cannot update properly.

`./op.sh: line 63: --data: command not found`

OS ubuntu 20.04 

![image](https://user-images.githubusercontent.com/64646367/130593626-947bc2d7-a30d-49aa-be23-90ce66d2ca1b.png)

**Comment by lifehome** [comment]
Hi there,

Thanks for the tip! I have actually fixed this issue, but not yet pushed on GitHub... Lemme push it first, and let's see if it gets fixed in your environment 😄 

-- Ivan

**Comment by lifehome** [comment]
@tapesi I have just pushed, commit b4d506a73f3ae6e1542f8cdd12752d8c34c5d8f3 should have fixed the `v4` and `v6` script.

PS: I haven't really dug deep into the dual stack script yet, but if you're really in a hurry, just run both script and put aside the dual stack script until it's fixed...

**Comment by lifehome** [comment]
Hi @tapesi,

Wonder if you have tested it out? Will be closing this issue if it's inactive for the next 3 days.

Thanks!

-- Ivan

**Comment by Roggstars** [comment]
Hi, just wanted to let you know that the error still persists for me (even though it might have been resolved for OP). Do you have any idea on this? Can I provide any additional information? Thank you for your great work, I really like this tool :)

**Comment by Roggstars** [comment]
To follow up on this, I tried to use the eval line from the v4/v6 files. This removes the error "--data: command not found", however, the update still does not come through on my cf record.

**Comment by Roggstars** [comment]
Hello again @lifehome,
I might miss something here, but this is what I have learned so far on the issue:
1. there has been an API update on Sep 2nd, so I am not exactly sure what actually changed there.
2. the command providing the records in lines 47 and 48 returns the string "curl" for me, so there is something wrong with the formatting I guess (primarily the ' and " symbols I would say based on some debugging, but I can't currently figure out why (I don't know that much about shell scripts, shame on me).
3. I guess for the (maybe) new API, the JSON data should not include the zone identifier itself, so it should just start with the type of the record instead (lines 72 and 73).

**Comment by lifehome** [comment]
Hi @Roggstars,

Glad to help! May I know your environment and setup? Mainly the shell, version of curl/grep and OS you are using :))  
Also if possible, please either screenshot the error output(with private info like your hostname redacted), or include the error in a code block:

<pre>
```
Type or paste logs/code inside here!
Please make sure to include the three " ` " symbol at the beginning and end of line to indicate a code block.
```
</pre>

I am also looking at the update you mentioned, but haven't found anything that affects the script yet, will keep you posted in this issue thread.

PS: I am not really familiar with bash, but thank you for liking my work! Really appreciate that!

-- Ivan

**Comment by Roggstars** [comment]
Hi Ivan,

so far I have tested the script both on my Raspberry Pi 3 running Ubuntu Server 20.04 for arm obviously, and on my main system running the latest arch 5.13.13-arch1-1 on x86. On the Pi, the command `apt-cache policy` returns _3.4-1_ for grep (is this really necessary? I can't see any grep usage in the dualstack script) and _7.68.0-1ubuntu2.6_ for curl. On arch, `pacman -Ss` returns 3.6-1 for grep and _7.78.0-1_ for curl. On arch I use fish as my shell, however the command substitution should not be affected by that as the file requests bash execution at the beginning with `#!/bin/bash`. I also get the same errors as on the Raspberry Pi running the default shell, so I don't expect any shell complications to cause this problem.

I have already figured out a working version, however I am not sure if I comply to your coding conventions or style. Are you interested in me sharing that version, and if so how do you prefer that? Should I just fork your project and create a new branch before creating a pull request here? What I have primarily done is replacing some of the `"'"` weirdness with `\'` or `\"`, this got me through the process. To debug the code I used `bash -x cfupdater-dualstack` and worked through the commands and their returns. Also, I have copied the code line by line in a shell, looking at the output with `echo` and executing the curl commands with `eval` in order to better visualize everything.

-- Julian

**Comment by lifehome** [comment]
Hi Julian @Roggstars,

I am sorry that you are running into this chaotic incident, but as I have mentioned earlier that the **dualstack** script is incomplete, so if it bugs, it's completely normal. (It's not right but it's okay)

Can you see if you can run both **v4** and **v6** scripts normally, to replace the single-piece of dualstack script for short term?

Meanwhile, I have jumped and see if the **v4** and **v6** script can run normally, I have then tested on macOS 11.5.2 with bash `3.2.57(1)-release (x86_64-apple-darwin20)`, and Arch Linux `5.13.13-arch1-1` with bash `5.1.8(1)-release (x86_64-pc-linux-gnu)`, both platforms can run just fine.

Again, I deeply apologize for the confusion, and will work on the dualstack script asap.

-- Ivan

**Comment by Roggstars** [comment]
Both v4 and v6 work fine for me, thanks :) I look forward to the update.

-- Julian
